### PR TITLE
Some minor suggestions

### PR DESCRIPTION
**Pull request by arseniiv**
Hi! Maybe these would be interesting to you.

Here is also a possible solution to #4.

### CODE REVIEW

**Comment by renatoathaydes** [comment]
Hi @arseniiv 
Thank you for the pull request!

I see you have quite a few different changes here. Normally, it would be better to make different pull requests for each different issue... but as the changes are not so large, I will try to review each commit separately and hope we can merge this soon!

**Comment by renatoathaydes** [comment]
I think we can merge all of your commits after you address my comments.
However, every change you make should be accompanied by a test proving that your changes work.

Could you please write some tests before we merge everything?

That would be wonderful!

Hope you can find your way around the tests I've written (using the `expect` function to test the parsers)... it's pretty easy to test all your changes (except the performance-related one, but I will trust you if you get me some numbers).

**Comment by arseniiv** [comment]
@renatoathaydes 

> Could you please write some tests before we merge everything?

Of course! (At least I’ll try :smile:) Maybe tomorrow, though. Got to go now.
Also I’ve addressed the current comments.

**Comment by arseniiv** [comment]
Seems I’ve done. Here is some numbers on two `letter`s: https://gist.github.com/arseniiv/7073d3c77d990ac39304 :1234:

(Unfortunately, I can’t check these new tests, since `ceylon.test 1.2.0` doesn’t work with 1.2.1, and Specks from Herd currently use 1.2.0, so I’d be needed to fork them too.)

**Comment by arseniiv** [comment]
Isn’t `AssertionError` enough? In https://github.com/arseniiv/parcey/commit/f291f794d2faec1f2b0ae5dea66079dcfd5a5301#diff-b17ca1ec0a515e17f209ecdc955de454 there is an assertion, it should fail in the second test.

**Comment by arseniiv** [comment]
Oh, one more suggestion: it seems we could use `Set`s in `oneOf`/`noneOf` if their first parameters were `{Character*}`, not `{Character+}`. However, it’s equivalent to more or less concise `satisfy(set.contains)`. Does it seem interesting?

**Comment by renatoathaydes** [comment]
I will have a look at that tonight. Thanks for your contributions, looks quite enough for a new release!

**Comment by arseniiv** [comment]
No problem :smile:

**Comment by renatoathaydes** [comment]
The test is failing but I can fix that! Merging.

**Comment by renatoathaydes** [comment]
> Oh, one more suggestion: it seems we could use Sets in oneOf/noneOf

Thanks for the advice... the code didn't use a `Set` because there was no `Set` implementations in the language module before 1.2 and I didn't feel like importing collections just for this. But now, with the `set` function in the language module, this needs to be fixed... just committed the change!

**Comment by renatoathaydes** [comment]
https://herd.ceylon-lang.org/modules/com.athaydes.parcey/0.4.0

@arseniiv  It's on Herd! Thanks for your help! This version should be much more efficient.... I hope... let me know if you notice some good speed improvements.

**Comment by arseniiv** [comment]
@renatoathaydes Ah, cool!

**Pull request merged**
